### ISSUE TITLE
Sonar ?

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/scenario-generator#4]
https://docs.sonarqube.org/display/PLUG/SonarPython ? 😆

**Comment by argenos** [comment]
Still can’t add the organization to my profile though, but I’m working on getting this running locally in the mean time 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by moriarty** [comment]
I checked again, and I saw I had created two HBRS-MAAS organizations, and you were only on one... so I added you to the second. I can’t tell the difference. ¯\_(ツ)_/¯ 

So maybe try again

**Comment by argenos** [comment]
No luck! Can you try adding me as owner?

**Comment by argenos** [comment]
Done!
